### ISSUE TITLE
What is the usage of `ExtendedFocusOnNavigate` component?

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1203]

**Comment by TheHadiAhmadi** [comment]
Blazor has `FocusOnNavigate` component which calls a js function when page changes. because we have only one Page (Default.razor) then It will only run on first time, and after navigate, autofocus wouldn't work.

The problem was this line: https://github.com/dotnet/aspnetcore/blob/ba48864ca3155fdb24955d5e6ca07a2b3c3a63d6/src/Components/Web/src/Routing/FocusOnNavigate.cs#L46

We created a component which does the same thing without checking page type.

**Comment by pournasserian** [comment]
@TheHadiAhmadi Is it just for focusing automatically on route change?

Is it to cover an known-issue in Blazor?

**Comment by TheHadiAhmadi** [comment]
@pournasserian yes it is required for route change. In static SRR mode we will not need this.

I didn't found issue related to thin in aspnetcore repository

**Comment by pournasserian** [comment]
@TheHadiAhmadi do we really need AutoFocus? Let's discuss in a meeting?

**Comment by TheHadiAhmadi** [comment]
we will need autofocus in future, in this stage of project, we don't need to worry about this. Also current implementation has some bugs.
I will revert changes for Autofocus to keep project's code clean.
