### ISSUE TITLE
`@bind-Value` doesn't working in SSR form submit (POST)

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1224]
In SSR form submit post method, built-in input component's name attribute automatically is set by Blazor engine. In below example:

`<InputText @bind-Value="Model.Email" Placeholder="Enter your email" />`

The rendered html will be:

`<input placeholder="Enter your email" name="Model.Email" class="valid" value="admin@example.com">`

The values will be set on the server for the `Model`.

But, in our component library the rendered result is:

`<input placeholder="Enter your email" name="Value" class="valid" value="admin@example.com">`

**And, SSR form won't be work.**

**Comment by pournasserian** [comment]
I have created a sample component inheriting built-in `InputText` component:
_**InputTest.razor**_
```
@inherits InputText
<h1>Test</h1>
@{
    base.BuildRenderTree(__builder);
}

```

And I used the component in setup page:
```
    <PluginForm Model="@Model" OnSubmit="OnSubmit" Name="@FORM_NAME" Title="@($"Welcome To FluentCMS {Model.Username}")">
        **<InputTest @bind-Value="Model.Username" Placeholder="Enter your username" />**
        <InputText @bind-Value="Model.Email" Placeholder="Enter your email" />
        <InputText @bind-Value="Model.Password" Placeholder="Enter your password" type="password" />
        <InputText @bind-Value="Model.AppTemplateName" />
        <InputText @bind-Value="Model.SiteTemplateName" />
        <InputText @bind-Value="Model.AdminDomain" />
        <PluginFormActions>
            <Button Block="true"  Color="Color.Primary" Type="ButtonType.Submit">
                Setup
            </Button>
        </PluginFormActions>
    </PluginForm>
```

The above code is working fine, I think there is a bug in our input components.

**Comment by ParsaGachkar** [comment]
Let's consider extending Microsoft's InputBase<T> instead of creating our own implementation.


https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.inputbase-1?view=aspnetcore-8.0

I believe InputText is a good reference for its implementation.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.inputtext?view=aspnetcore-8.0

https://github.com/dotnet/aspnetcore/blob/3f1acb59718cadf111a0a796681e3d3509bb3381/src/Components/Web/src/Forms/InputText.cs
