### ISSUE TITLE
Why should we have `StopPropagation` property in `Button` component

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1384]

**Comment by TheHadiAhmadi** [comment]
@pournasserian table rows are clickable and have default actions, inside table rows we have some action buttons.

Assume clicking table row navigates to Detail page. 
When we click on Edit page, it would navigate to Detail page because both elements have listeners for click event (Button and Table row) and always page navigates to Detail page.

When StopPropagation is true, only action of button executes.

**Comment by TheHadiAhmadi** [comment]
@pournasserian table rows are clickable and have default actions, inside table rows we have some action buttons.

Assume clicking table row navigates to Detail page. 
When we click on Edit page button of a row, it would navigate to Detail page because both elements have listeners for click event (Button and Table row) and always page navigates to Detail page.

When StopPropagation is true, only action of button executes.

**Comment by pournasserian** [comment]
> @pournasserian table rows are clickable and have default actions, inside table rows we have some action buttons.
> 
> Assume clicking table row navigates to Detail page. 
> When we click on Edit page button of a row, it would navigate to Detail page because both elements have listeners for click event (Button and Table row) and always action of TableRow executes.
> 
> When StopPropagation is true, only action of button executes.

It is not a good user experience: the user would like to select one or some fields/rows from a table to copy and paste somewhere.

**Comment by abdolian** [comment]
@pournasserian This support is used for situations where parents and their children have a similar event.
Suppose there is a button in a card or any other parent element and you want to distinguish between parent and child clicks, then there is no way but StopPropagation.
If you are sure that this will not happen, we can remove it.
