### ISSUE TITLE
Develop multiple-selection content type field

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#1665]

**Comment by TheHadiAhmadi** [comment]
PocketBase: Show error when change type from multiple to single
![image](https://github.com/fluentcms/FluentCMS/assets/42554876/315ba9a4-f0a4-4896-90cc-5e06b627a31c)


Directus: It is not important for it. first tries to fetch data from db, if it works with current type, it will set initial values, otherwise it will skip value and update when content saved.

for Block Editor component it stores this JSON
![image](https://github.com/fluentcms/FluentCMS/assets/42554876/d5b1a952-d3de-4a74-ac7d-ff83a5bb1668)
When I change it's type to Checkbox Group, all items are unchecked and after save, value changes to Array of string.

Webflow: It doesn't support Multiple selection mode, but it has (Image, Multiple Image), (Reference, Multi Reference) types.
To have multiple selection field we should create new ContentType and use Multi Reference type.

**Comment by TheHadiAhmadi** [comment]
@pournasserian We can have separate Field type for single/multiple modes.

String
Number
Boolean
Date
Media
Media (Multiple)
Enumeration / Options / Select
Enumeration (Multiple) / Options (Multiple) / Select (Multiple)
Refernece
Reference (Multiple) / Multi Reference / References
JSON --> for complex types we can have json type and show `CodeEditor` for Content form.
