### ISSUE TITLE
Create and define "issue" template

### ISSUE THREAD

**Issue by pournasserian** [fluentcms/FluentCMS#8]

**Comment by ParsaGachkar** [comment]
Briefly describe the issue or feature request.

# Description

Provide a detailed explanation of the issue or feature. Include any relevant context, screenshots, or error messages.

# Steps to Reproduce (for Bugs)

Describe the steps to reproduce the issue.

Include any specific inputs, configurations, or conditions.

Mention the expected behavior and what actually occurred.

# Expected Behavior (for Bugs)

Describe what should happen when the issue is resolved, or the feature is implemented.

# Developer Console Logs (for Bugs) (If Applicable)

Include any relevant logs from the browser’s developer console. These logs can help pinpoint JavaScript errors or unexpected behavior.

# Server Logs (for Bugs) (If Applicable)

If applicable, provide logs from the server-side. This could be application logs, database logs, or any other relevant logs.

# Additional Information

Add any other relevant details, such as environmental information, related issues, or workarounds.
